In [1]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import gc
import sys
sys.path.append('./tools')

from load_data import load_split_data, load_set_data, load_test_frames, load_frames_data
from input_distortion import input_distortion,pretraining_input_distortion
from copy import copy

from PretrainingMAE import PretrainingMAE
from MAE import MAE

In [2]:
# Load data for training
train_seq, val_seq, test_seq = load_split_data() 

data_train = load_set_data(train_seq)
data_val = load_set_data(val_seq)

In [3]:
# Define models for Pretraining
pretraining =  PretrainingMAE(data_train,data_val)
del data_train, data_val

In [4]:
# Pretraing RGB Channels independently
pretraining.pretrain_red_channel()
pretraining.pretrain_green_channel()
pretraining.pretrain_blue_channel()

----------------------------------------------------------------
('Epoch', 0, 'completed out of', 300)
('Training Loss (per epoch): ', 719884.06)
('Validation Loss (per pixel): ', 0.016322946548461913)
('Epoch Time [seconds]:', 20)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 1, 'completed out of', 300)
('Training Loss (per epoch): ', 416627.56)
('Validation Loss (per pixel): ', 0.012740684747695923)
('Epoch Time [seconds]:', 19)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 2, 'completed out of', 300)
('Training Loss (per epoch): ', 341497.31)
('Validation Loss (per pixel): ', 0.011040016412734985)
('Epoch Time [seconds]:', 19)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 3, 'completed out of', 300)
('T

In [5]:
# Pretraing Inverse-Depth Channel
pretraining.pretrain_depth_channel()

Depth Pretraining
----------------------------------------------------------------
('Epoch', 0, 'completed out of', 300)
('Training Loss (per epoch): ', 21059.498)
('Validation Loss (per pixel): ', 0.0005637284079382962)
('Epoch Time [seconds]:', 20)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 1, 'completed out of', 300)
('Training Loss (per epoch): ', 10600.312)
('Validation Loss (per pixel): ', 0.00046124269514007739)
('Epoch Time [seconds]:', 20)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 2, 'completed out of', 300)
('Training Loss (per epoch): ', 8838.043)
('Validation Loss (per pixel): ', 0.00039419065401759165)
('Epoch Time [seconds]:', 20)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 3, 'compl

In [6]:
# Pretraing Semantic Channels independently
pretraining.pretrain_gnd_channel()
pretraining.pretrain_obj_channel()
pretraining.pretrain_bld_channel()
pretraining.pretrain_veg_channel()
pretraining.pretrain_sky_channel()

----------------------------------------------------------------
('Epoch', 0, 'completed out of', 300)
('Training Loss (per epoch): ', 1125835.1)
('Validation Loss (per pixel): ', 0.019170278310775758)
('Epoch Time [seconds]:', 19)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 1, 'completed out of', 300)
('Training Loss (per epoch): ', 583673.06)
('Validation Loss (per pixel): ', 0.01445832371711731)
('Epoch Time [seconds]:', 21)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 2, 'completed out of', 300)
('Training Loss (per epoch): ', 467757.94)
('Validation Loss (per pixel): ', 0.012162513732910156)
('Epoch Time [seconds]:', 21)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 3, 'completed out of', 300)
('Tr

In [5]:
# Pretraing Semantic AutoEncoder
pretraining.pretrain_shared_semantics(run='20171116-093220')

INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_gnd.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_gnd.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_obj.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_obj.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_bld.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_bld.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_veg.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_veg.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_sky.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/20171116-093220/pretrained_sky.ckpt


('Epoch', 0, 'completed out of', 300)
('Training Loss (per epoch): ', 3824156.0)
('Validation Loss (per pixel): ', 0.091018743515014655)
('Epoch Time [seconds]:', 146)
-----------------------------------------------------------------
('Epoch', 1, 'completed out of', 300)
('Training Loss (per epoch): ', 2211260.2)
('Validation Loss (per pixel): ', 0.07047913551330566)
('Epoch Time [seconds]:', 140)
-----------------------------------------------------------------
('Epoch', 2, 'completed out of', 300)
('Training Loss (per epoch): ', 1815762.1)
('Validation Loss (per pixel): ', 0.061315703392028811)
('Epoch Time [seconds]:', 150)
-----------------------------------------------------------------
('Epoch', 3, 'completed out of', 300)
('Training Loss (per epoch): ', 1594984.8)
('Validation Loss (per pixel): ', 0.055165505409240721)
('Epoch Time [seconds]:', 141)
-----------------------------------------------------------------
('Epoch', 4, 'completed out of', 300)
('Training Loss (per epoch)

In [2]:
#del pretraining

# Load data for training and testing
train_seq, val_seq, test_seq = load_split_data()

data_train = load_set_data(train_seq)
data_val = load_set_data(val_seq)
#data_test = load_set_data(test_seq)

In [2]:
# Define Full Model
mae = MAE()

In [4]:
# Train MultiModal AutoEncoder
mae.train_model(data_train,data_val,load = 'pretrained')
del data_train, data_val

INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_red.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_red.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_green.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_green.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_blue.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_blue.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_depth.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_depth.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_shared_semantics.ckpt


INFO:tensorflow:Restoring parameters from models/pretraining/pretrained_models/pretrained_shared_semantics.ckpt


----------------------------------------------------------------
('Epoch', 0, 'completed out of', 600)
('Training Loss (per epoch): ', 16934166.0)
('Validation Loss (per pixel): ', 0.060032256)
('Epoch Time [seconds]:', 520)
-----------------------------------------------------------------
----------------------------------------------------------------
('Epoch', 1, 'completed out of', 600)
('Training Loss (per epoch): ', 13642125.0)


KeyboardInterrupt: 

In [4]:
# Continue training (refining) a full model
mae.train_model(data_train,data_val,load = 'continue',run = '20171118-192527')
del data_train, data_val

INFO:tensorflow:Restoring parameters from models/full/20171118-192527/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171118-192527/fullmodel.ckpt


InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1080] rhs shape= [1024,1080]
	 [[Node: save/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@blue_dc_layer_bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](blue_dc_layer_bias, save/RestoreV2_4)]]

Caused by op u'save/Assign_4', defined at:
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 405, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 260, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 175, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-107737db1b65>", line 2, in <module>
    mae.train_model(data_train,data_val,load = 'continue',run = '20171118-192527')
  File "MAE.py", line 680, in train_model
    'full_dc_layer_bias':self.full_dc_layer['bias']})
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ccadena/Software/virtualenv_python/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1080] rhs shape= [1024,1080]
	 [[Node: save/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@blue_dc_layer_bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](blue_dc_layer_bias, save/RestoreV2_4)]]


In [ ]:
# Evaluate full MAE
#fullmodel = '20171123-153406'
fullmodel = '20171016-131619'
mae.evaluate(data_test,run=fullmodel)

In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171016-131619'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171016-131619/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171016-131619/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 11.006707114244335)
('Error (Relative Error):', 0.33741376670909767)
Intersection over Union per class:
[ 0.7038052   0.27798119  0.44027053  0.63286233  0.68612366]
('Intersection: ', array([ 170791.,   39100.,   76685.,  209473.,   49228.]))
('Union: ', array([ 242668.,  140657.,  174177.,  330993.,   71748.]))


In [3]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171123-153406'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171123-153406/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171123-153406/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 10.963728795627658)
('Error (Relative Error):', 0.33346320718941441)
Intersection over Union per class:
[ 0.71064738  0.28384125  0.47020717  0.66551782  0.72450736]
('Intersection: ', array([ 169149.,   39379.,   81367.,  217621.,   50922.]))
('Union: ', array([ 238021.,  138736.,  173045.,  326995.,   70285.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171125-175601'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171125-175601/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171125-175601/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 11.222127732555723)
('Error (Relative Error):', 0.34759261600560032)
Intersection over Union per class:
[ 0.71097024  0.27460326  0.47529549  0.66467048  0.72887288]
('Intersection: ', array([ 169806.,   37393.,   82998.,  217873.,   50602.]))
('Union: ', array([ 238837.,  136171.,  174624.,  327791.,   69425.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171127-120921'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171127-120921/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171127-120921/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 11.29823816031405)
('Error (Relative Error):', 0.34455115439111533)
Intersection over Union per class:
[ 0.70911258  0.28536439  0.46225279  0.66399237  0.72563802]
('Intersection: ', array([ 167174.,   40080.,   80193.,  218575.,   50725.]))
('Union: ', array([ 235751.,  140452.,  173483.,  329183.,   69904.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171130-101151'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171130-101151/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171130-101151/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 10.953385804026116)
('Error (Relative Error):', 0.32709985372130534)
Intersection over Union per class:
[ 0.6919677   0.26031545  0.39775221  0.6120867   0.70642241]
('Intersection: ', array([ 165637.,   37052.,   70321.,  210111.,   49937.]))
('Union: ', array([ 239371.,  142335.,  176796.,  343270.,   70690.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20171204-112636'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20171204-112636/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20171204-112636/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 10.932261421136749)
('Error (Relative Error):', 0.33293540956244372)
Intersection over Union per class:
[ 0.67746241  0.25235526  0.35142375  0.5963253   0.67595991]
('Intersection: ', array([ 162425.,   38358.,   61794.,  206743.,   49170.]))
('Union: ', array([ 239755.,  152000.,  175839.,  346695.,   72741.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20180104-101318'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20180104-101318/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20180104-101318/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 11.044872759547198)
('Error (Relative Error):', 0.32864092977923864)
Intersection over Union per class:
[ 0.71551497  0.29718248  0.43731395  0.65133384  0.72975751]
('Intersection: ', array([ 165309.,   41273.,   75804.,  221036.,   50408.]))
('Union: ', array([ 231035.,  138881.,  173340.,  339359.,   69075.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20180103-112915'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20180103-112915/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20180103-112915/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 11.179307568951767)
('Error (Relative Error):', 0.34371950269581653)
Intersection over Union per class:
[ 0.71155855  0.29272114  0.45169057  0.65803784  0.72409627]
('Intersection: ', array([ 169632.,   40541.,   78979.,  215639.,   50938.]))
('Union: ', array([ 238395.,  138497.,  174852.,  327700.,   70347.]))


In [2]:
# Load data for testing by frames
test_frames = load_test_frames()
data_test_frames = load_frames_data(test_frames)

# Evaluate full MAE
fullmodel = '20180105-133937'

if 'mae' not in locals():
    mae = MAE()
    
mae.evaluate_per_frame(data_test_frames,run=fullmodel)

INFO:tensorflow:Restoring parameters from models/full/20180105-133937/fullmodel.ckpt


INFO:tensorflow:Restoring parameters from models/full/20180105-133937/fullmodel.ckpt


('Size of Test Set:', 697)
('Error (RMS):', 10.816119286224517)
('Error (Relative Error):', 0.33687156570305493)
Intersection over Union per class:
[ 0.6955334   0.27342221  0.41049532  0.61668113  0.71071823]
('Intersection: ', array([ 168301.,   38701.,   73179.,  207565.,   49606.]))
('Union: ', array([ 241974.,  141543.,  178270.,  336584.,   69797.]))


In [ ]:
import basic_routines as BR

im = BR.color2image(data_test_frames[0]['xcr'],data_test_frames[0]['xcg'],data_test_frames[0]['xcb'])
imd = BR.depth2image(data_test_frames[0]['xid'],data_test_frames[0]['xmask'])
ims = BR.sem2image(data_test_frames[0]['sem'])

%matplotlib inline

fig,axes = plt.subplots(3,1)
axes[0].imshow(im)
axes[0].set_title('Image')

axes[1].imshow(imd)
axes[1].set_title('Inverse Depth')

axes[2].imshow(ims, vmin=1, vmax=6)
axes[2].set_title('Semantics')

plt.show()

In [ ]:
#a = np.reshape(pretraining.imr_val[0],(60,18))
#print a[1]
#np.reshape(pretraining.imr_val)
#print np.dstack((imr,img,imb)).shape
print data_val[0][0]['xcgLeft']

x = horizontal_mirroring(data_val[0][0]['xcgLeft'],18,60)

print x

In [ ]:
'''
indmirror = np.linspace(0,18*60-1,18*60).astype(int)
indmirror = np.reshape(indmirror,(60,18))
indmirror = indmirror.T
indmirror = np.fliplr(indmirror)
indmirror = indmirror.T
indmirror = np.reshape(indmirror,(18*60))
'''
x = pretraining.imr_train[4,:]#data_val[0][0]['xcgLeft']
x1 = pretraining.imr_train[5,:]

%matplotlib inline

fig,axes = plt.subplots(1,2)
axes[0].imshow(np.reshape(x,(60,18)).T)
axes[0].set_title('im1')

axes[1].imshow(np.reshape(x1,(60,18)).T)
axes[1].set_title('im2')

plt.show()

ind = np.arange(0,10)
imr_in = copy(pretraining.imr_train[ind,:])
imr_batch = copy(pretraining.imr_train[ind,:])
ind_rand_who = np.random.choice(ind,10/2,replace=False)
imr_in = horizontal_mirroring(imr_in,ind_rand_who)
imr_batch = horizontal_mirroring(imr_batch,ind_rand_who)

x = imr_in[4,:]#data_val[0][0]['xcgLeft']
x1 = imr_in[5,:]



fig,axes = plt.subplots(1,2)
axes[0].imshow(np.reshape(x,(60,18)).T)
axes[0].set_title('im1')

axes[1].imshow(np.reshape(x1,(60,18)).T)
axes[1].set_title('im2')

plt.show()

ind_rand_who = np.random.choice(ind,10/2,replace=False)
imr_in = zeroing_channel(imr_in,ind_rand_who)

x = imr_in[4,:]#data_val[0][0]['xcgLeft']
x1 = imr_batch[4,:]



fig,axes = plt.subplots(1,2)
axes[0].imshow(np.reshape(x,(60,18)).T)
axes[0].set_title('im1')

axes[1].imshow(np.reshape(x1,(60,18)).T)
axes[1].set_title('im2')

plt.show()


In [ ]:


print mae.imr_val[0].shape
print mae.depth_mask_val[0].shape
print mae.depth_val[0].shape


In [4]:
pretraining.run

'20171211-105144'